# Generated by Django 2.1.5 on 2019-02-12 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='link',
            field=models.URLField(default='', verbose_name='Url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='number',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published'),
            preserve_default=False,
        ),
    ]
