# Generated by Django 2.1.5 on 2019-02-12 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0002_auto_20190212_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='link',
            field=models.URLField(default='#', verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='number',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published'),
        ),
    ]
