# Generated by Django 2.1.5 on 2019-02-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0003_auto_20190212_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='poll',
            field=models.IntegerField(default=0),
        ),
    ]
